export const REQUEST_GET_ITEM = 'REQUEST_GET_ITEM'
export const SUCCESS_GET_ITEM = 'SUCCESS_GET_ITEM'
export const FAILURE_GET_ITEM = 'FAILURE_GET_ITEM'

export const REQUEST_SET_ITEM = 'REQUEST_SET_ITEM'
export const SUCCESS_SET_ITEM = 'SUCCESS_SET_ITEM'
export const FAILURE_SET_ITEM = 'FAILURE_SET_ITEM'

export const REQUEST_CLEAR_DB = 'REQUEST_CLEAR_DB'
export const SUCCESS_CLEAR_DB = 'SUCCESS_CLEAR_DB'
export const FAILURE_CLEAR_DB = 'FAILURE_CLEAR_DB'
